name: Build Browser Extensions

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint (if configured)
      run: |
        if [ -f "eslint.config.js" ] || [ -f ".eslintrc.js" ] || [ -f ".eslintrc.json" ]; then
          npm run lint || echo "ESLint not configured in package.json"
        else
          echo "ESLint not configured"
        fi
      continue-on-error: true
      
    - name: Type check
      run: |
        if [ -f "tsconfig.json" ]; then
          npx tsc --noEmit
        else
          echo "TypeScript not configured"
        fi

  build-chrome:
    name: Build Chrome Extension
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Chrome extension
      run: npm run build:chrome
      
    - name: Upload Chrome build
      uses: actions/upload-artifact@v4
      with:
        name: chrome-extension
        path: build/chrome/
        retention-days: 30

  build-firefox:
    name: Build Firefox Extension
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Firefox extension
      run: npm run build:firefox
      
    - name: Upload Firefox build
      uses: actions/upload-artifact@v4
      with:
        name: firefox-extension
        path: build/firefox/
        retention-days: 30

  build-edge:
    name: Build Edge Extension
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Edge extension
      run: npm run build:edge
      
    - name: Upload Edge build
      uses: actions/upload-artifact@v4
      with:
        name: edge-extension
        path: build/edge/
        retention-days: 30

  build-all:
    name: Build All Extensions
    runs-on: ubuntu-latest
    needs: [build-chrome, build-firefox, build-edge]
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build and package all extensions
      run: npm run package

    - name: Upload packaged extensions
      uses: actions/upload-artifact@v4
      with:
        name: packaged-extensions
        path: packages/
        retention-days: 90
